// Music Genres with South African Orientation
export const GENRES = [
  // Traditional South African Genres
  'Amapiano',
  'Gqom',
  'Afro House',
  'Kwaito',
  'Bacardi',
  'Maskandi',
  'Isicathamiya',
  'Mbaqanga',
  'Bubblegum',
  'Boeremusiek',
  'Cape Jazz',
  'Marabi',
  'Mbaqanga',
  'Soweto Gospel',
  'Township Jive',

  // Popular African Genres
  'Afro Pop',
  'Afro Soul',
  'Afro Jazz',
  'Afro Beat',
  'Afro Tech',
  'Deep House',
  'Tech House',
  'Progressive House',
  'Afro Deep',
  'Afro Minimal',

  // International Genres
  'Hip Hop',
  'R&B',
  'Pop',
  'Electronic',
  'Jazz',
  'Soul',
  'Reggae',
  'Rock',
  'Alternative',
  'Indie',
  'Folk',
  'Blues',
  'Gospel',
  'Classical',
  'Country',
  'Funk',
  'Punk',
  'Metal',
  'Ambient',
  'Techno',
  'House',
  'Trance',
  'Dubstep',
  'Trap',
  'Drill',
  'Latin',
  'World',
  'Other',
];

// Genre categories for better organization
export const GENRE_CATEGORIES = {
  'Traditional African': [
    'Amapiano',
    'Gqom',
    'Afro House',
    'Kwaito',
    'Bacardi',
    'Maskandi',
    'Isicathamiya',
    'Mbaqanga',
    'Bubblegum',
    'Boeremusiek',
    'Cape Jazz',
    'Marabi',
    'Soweto Gospel',
    'Township Jive',
  ],
  'Modern African': [
    'Afro Pop',
    'Afro Soul',
    'Afro Jazz',
    'Afro Beat',
    'Afro Tech',
    'Deep House',
    'Tech House',
    'Progressive House',
    'Afro Deep',
    'Afro Minimal',
  ],
  International: [
    'Hip Hop',
    'R&B',
    'Pop',
    'Electronic',
    'Jazz',
    'Soul',
    'Reggae',
    'Rock',
    'Alternative',
    'Indie',
    'Folk',
    'Blues',
    'Gospel',
    'Classical',
    'Country',
    'Funk',
    'Punk',
    'Metal',
    'Ambient',
    'Techno',
    'House',
    'Trance',
    'Dubstep',
    'Trap',
    'Drill',
    'Latin',
    'World',
    'Other',
  ],
};

export default GENRES;
