import js from '@eslint/js';
import nextCoreWebVitals from 'eslint-config-next/core-web-vitals';
import prettierConfig from 'eslint-config-prettier';
import jsxA11y from 'eslint-plugin-jsx-a11y';
import prettierRecommended from 'eslint-plugin-prettier/recommended';
import react from 'eslint-plugin-react';
import reactHooks from 'eslint-plugin-react-hooks';
import globals from 'globals';

/**
 * ESLint 9 flat config.
 *
 * Replaces `.eslintrc.json` + `.eslintignore`, both of which ESLint 9 ignores
 * in flat mode. This is a FAITHFUL port, not a re-think: the rule set, the
 * severities and all four override blocks are carried across unchanged, and
 * the migration was accepted only once `eslint .` produced byte-identical
 * findings to the eslintrc run (15 warnings, all @next/next/no-img-element,
 * 0 errors — same files, same lines).
 *
 * Why this had to happen at all: `eslint-config-next@16` declares
 * `peerDependencies.eslint: ">=9.0.0"`, so aligning it with Next 16 forces
 * ESLint 9, and ESLint 9 defaults to flat config.
 *
 * ESLint 9 was chosen over 10 deliberately. Every plugin here caps its peer
 * range at `^9` (react, react-hooks, jsx-a11y, @typescript-eslint 8.x), so
 * ESLint 10 would break peer resolution across the board for no benefit.
 *
 * ORDER IS LOAD-BEARING. `prettierConfig` (eslint-config-prettier) turns OFF
 * every stylistic rule the earlier configs turn on, and `prettierRecommended`
 * then re-adds `prettier/prettier` as the single formatting authority. Both
 * must stay after the recommended sets; moving them earlier silently
 * reintroduces rules that fight Prettier.
 */
export default [
  // `.eslintignore` is not read in flat mode — these are its entries. Build
  // output, vendored/generated files and configs that were never linted.
  {
    ignores: [
      'node_modules/**',
      '.next/**',
      'out/**',
      'build/**',
      'dist/**',
      'coverage/**',
      '.nyc_output/**',
      'jspm_packages/**',
      '.cache/**',
      '.parcel-cache/**',
      '.nuxt/**',
      '.out/**',
      '.storybook-out/**',
      'tmp/**',
      'temp/**',
      'prisma/migrations/**',
      '**/*.generated.*',
      'next.config.mjs',
      'postcss.config.js',
      // Regenerated by Next on every build and marked "should not be edited".
      // Next 16 rewrites it with an import whose quote style prettier rejects,
      // which would otherwise fail `yarn check-all` permanently.
      'next-env.d.ts',
      // Nested git worktrees created by AI coding tools.
      '.claude/**',
      '.cursor/**',
      '.design-sync/**',
    ],
  },

  js.configs.recommended,
  ...nextCoreWebVitals,

  // The eslintrc file also extended plugin:react/recommended,
  // plugin:react-hooks/recommended and plugin:jsx-a11y/recommended. Their RULE
  // SETS are spread here rather than the configs being included wholesale,
  // because `eslint-config-next` already registers all three plugins (plus
  // `import`, `@next/next` and `@typescript-eslint`) and flat config throws
  // `Cannot redefine plugin` on a second registration — where eslintrc silently
  // let the last one win. Spreading only `.rules` keeps every recommended rule
  // that was active before without touching plugin registration.
  //
  // `files` MUST match eslint-config-next's own glob. Flat config scopes
  // plugins per config object, so applying a `react/*` rule to a file the Next
  // config does not cover fails with "could not find plugin". Note that glob
  // excludes `.cjs`, which `scripts/lib/prisma.cjs` is.
  {
    files: ['**/*.{js,jsx,mjs,ts,tsx,mts,cts}'],
    rules: {
      ...react.configs.flat.recommended.rules,
      ...reactHooks.configs['recommended-latest'].rules,
      ...jsxA11y.flatConfigs.recommended.rules,
    },
  },

  // Formatting authority — must stay after the recommended sets above.
  prettierConfig,
  prettierRecommended,

  {
    languageOptions: {
      ecmaVersion: 2022,
      sourceType: 'module',
      parserOptions: {
        ecmaFeatures: { jsx: true },
      },
      globals: {
        ...globals.browser,
        ...globals.node,
      },
    },
    settings: {
      react: { version: 'detect' },
    },
    rules: {
      // General JavaScript — applies to every linted file, including .cjs.
      'no-console': ['error', { allow: ['warn', 'error'] }],
      'no-debugger': 'error',
      'no-duplicate-imports': 'error',
      'no-unused-expressions': 'error',
      // `caughtErrors` is pinned to ESLint 8's default. ESLint 9 flipped it
      // from 'none' to 'all', which turns every unused `catch (error)` binding
      // into an error — 31 of them here, none of which are new code or new
      // problems. Pinning keeps this migration faithful; tightening it to
      // 'all' is a separate, deliberate cleanup (use `catch {}` or `_error`).
      'no-unused-vars': [
        'error',
        { argsIgnorePattern: '^_', caughtErrors: 'none' },
      ],
      'no-var': 'error',
      'prefer-const': 'error',
      'prefer-arrow-callback': 'error',
      'prefer-template': 'error',
      'prettier/prettier': 'error',

      // New in ESLint 9, and BLOCKED by the TypeScript config rather than by
      // the code. It wants `throw new Error(msg, { cause: err })`, but
      // tsconfig sets target/lib to ES2020 and the `cause` option is ES2022 —
      // tsc rejects the two-argument form with TS2554. Only 2 call sites
      // (lyrics-processing-agent.ts, track-metadata-agent.ts). Enable this the
      // same day tsconfig moves to ES2022; bumping the compilation target is a
      // repo-wide change that does not belong in a lint migration.
      'preserve-caught-error': 'off',
    },
  },

  // Plugin-scoped rules. Same glob as eslint-config-next for the reason above.
  {
    files: ['**/*.{js,jsx,mjs,ts,tsx,mts,cts}'],
    rules: {
      // React
      'react/react-in-jsx-scope': 'off',
      'react/prop-types': 'off',
      'react/jsx-uses-react': 'off',
      'react/jsx-uses-vars': 'error',
      'react/jsx-key': 'error',
      'react/jsx-no-duplicate-props': 'error',
      'react/jsx-no-undef': 'error',
      'react/no-children-prop': 'error',
      'react/no-danger-with-children': 'error',
      'react/no-deprecated': 'error',
      'react/no-direct-mutation-state': 'error',
      'react/no-find-dom-node': 'error',
      'react/no-is-mounted': 'error',
      'react/no-render-return-value': 'error',
      'react/no-string-refs': 'error',
      'react/no-unescaped-entities': 'error',
      'react/no-unknown-property': 'error',
      'react/require-render-return': 'error',

      // React Hooks
      'react-hooks/rules-of-hooks': 'error',
      'react-hooks/exhaustive-deps': 'off',

      // --- React Compiler rules: DEFERRED, NOT DISMISSED ------------------
      // eslint-config-next@16 enables 16 react-hooks rules where v15 enabled
      // two. The 14 below are the new ones, and they currently flag 110 real
      // errors across ~125 files:
      //
      //   set-state-in-effect          51
      //   immutability                 37
      //   static-components            13
      //   refs                          5
      //   purity                        2
      //   preserve-manual-memoization   2
      //
      // These are genuine code-quality signals, not noise. They are switched
      // off HERE, in one visible block, rather than silently absorbed — fixing
      // them means changing component behaviour across a large surface with no
      // integration tests to catch regressions, which is a different change
      // from a lint-config migration and belongs in its own reviewable batches.
      // Turn them on one at a time; the counts above are the work remaining.
      'react-hooks/static-components': 'off',
      'react-hooks/use-memo': 'off',
      'react-hooks/preserve-manual-memoization': 'off',
      'react-hooks/incompatible-library': 'off',
      'react-hooks/immutability': 'off',
      'react-hooks/globals': 'off',
      'react-hooks/refs': 'off',
      'react-hooks/set-state-in-effect': 'off',
      'react-hooks/error-boundaries': 'off',
      'react-hooks/purity': 'off',
      'react-hooks/set-state-in-render': 'off',
      'react-hooks/unsupported-syntax': 'off',
      'react-hooks/config': 'off',
      'react-hooks/gating': 'off',

      // Accessibility
      'jsx-a11y/alt-text': 'error',
      'jsx-a11y/anchor-has-content': 'error',
      'jsx-a11y/anchor-is-valid': 'error',
      'jsx-a11y/aria-props': 'error',
      'jsx-a11y/aria-proptypes': 'error',
      'jsx-a11y/aria-unsupported-elements': 'error',
      'jsx-a11y/click-events-have-key-events': 'warn',
      'jsx-a11y/heading-has-content': 'error',
      'jsx-a11y/html-has-lang': 'error',
      'jsx-a11y/img-redundant-alt': 'error',
      'jsx-a11y/no-access-key': 'error',
      'jsx-a11y/role-has-required-aria-props': 'error',
      'jsx-a11y/role-supports-aria-props': 'error',

      'prettier/prettier': 'error',
    },
  },

  // --- overrides, carried across from .eslintrc.json ------------------------

  {
    files: ['*.config.js', '*.config.mjs'],
    rules: { 'no-console': 'error' },
  },

  {
    files: ['src/lib/utils/logger.ts'],
    rules: { 'no-console': 'off' },
  },

  {
    files: ['scripts/**/*.{js,mjs,cjs,ts}'],
    rules: { 'no-console': 'off' },
  },

  {
    files: [
      '**/*.test.{js,jsx,ts,tsx}',
      '**/__tests__/**/*.{js,jsx,ts,tsx}',
      'jest.setup.js',
    ],
    languageOptions: {
      globals: {
        ...globals.jest,
        ...globals.node,
      },
    },
    rules: {
      'no-unused-vars': [
        'error',
        { argsIgnorePattern: '^_', caughtErrors: 'none' },
      ],
    },
  },
];
